### ISSUE TITLE
🐞[BUG]: 'RouterState' class should be decorated with @Injectable() right after the @State() decorator

### ISSUE THREAD

**Issue by emzet** [ngxs/store#1866]
### Affected Package
The issue is caused by package @ngxs/router-plugin

### Description
When running `ngcc`, there is an compilation error (see below) also when using `Jest` in Angular via `jest-preset-angular` there is warning in console (due to compilation error).

## 🔬 Minimal Reproduction
Console log is enough to determine the the problem (but in case if really needed I can prepare stackblitz demo).

## 🔥 Exception or Error
Error when running ngcc:

<pre><code>
Error: Failed to compile entry-point @ngxs/router-plugin (`esm5` as esm5) due to compilation errors:
node_modules/@ngxs/router-plugin/esm5/src/router.module.js:9:5 - error NG3004: Unable to import class NgxsFeatureModule.
  The symbol is not exported from {PROJECT_PATH}/node_modules/@ngxs/store/index.d.ts (module '@ngxs/store').

9 var NgxsRouterPluginModule = /** @class */ (function () {
      ~~~~~~~~~~~~~~~~~~~~~~

  node_modules/@ngxs/store/src/modules/ngxs-feature.module.d.ts:11:1
     11 export declare class NgxsFeatureModule {
        ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
     12     constructor(_store: Store, internalStateOperations: InternalStateOperations, factory: StateFactory, states: StateClassInternal<any, any>[][] | undefined, lifecycleStateManager: LifecycleStateManager);
        ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    ...
     16     static ɵinj: ɵngcc0.ɵɵInjectorDeclaration<NgxsFeatureModule>;
        ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
     17 }
        ~
    The class is declared here.
</code></pre>

Warning when running test via Jest:
<pre><code>
  ● Console

    console.warn
      'RouterState' class should be decorated with @Injectable() right after the @State() decorator

      at ensureStateClassIsInjectable (node_modules/@ngxs/store/bundles/@ngxs/store/src/ivy/ivy-enabled-in-dev-mode.ts:19:15)
      at node_modules/@ngxs/store/bundles/@ngxs/store/src/decorators/state.ts:50:7
      at __decorate (node_modules/node_modules/tslib/tslib.es6.js:56:95)
      at node_modules/@ngxs/router-plugin/bundles/@ngxs/router-plugin/src/router.state.ts:52:25
      at node_modules/@ngxs/router-plugin/bundles/@ngxs/router-plugin/src/router.state.ts:301:2
      at node_modules/@ngxs/router-plugin/bundles/ngxs-router-plugin.umd.js:2:68
      at Object.<anonymous> (node_modules/@ngxs/router-plugin/bundles/ngxs-router-plugin.umd.js:5:2)
</code></pre>

## Environment

<pre><code>
Libs:
- @angular/core version: 13.3.11
- @ngxs/store version: 3.7.4
- @ngxs/router-plugin: 3.7.4
- jest-preset-angular: 12.1.0
- jest: 28.1.1
 
For Tooling issues:
- Node version: 16.15.1
- Platform: Windows x64

**Comment by markwhitfeld** [comment]
@arturovt Is your fix for both the issues mentioned here, or just the one?
If the ngcc issue is a different issue, then possibly it should be split out into a separate issue.

**Comment by arturovt** [comment]
I have never seen this ngcc issue. Reinstalling node_modules could’ve helped.

**Comment by codeuniquely** [comment]
I have the same issue on several projects old ones which have been updated to angular 13 with node_modules removed and reinstalled (as suggested above) and it also happens on a fresh angular project (angular 13).

**Comment by arturovt** [comment]
I can’t give any more advice rather than guessing what might happen. Provide a minimal reproducible example.

**Comment by codeuniquely** [comment]
I looks like this merge might actually fix the issue
https://github.com/ngxs/store/pull/1867/commits/0946003061f048ca5b751ae895d74f4f35d9c490

**Comment by codeuniquely** [comment]
This example shows the issue:

npm install 
and
npm test

[example.zip](https://github.com/ngxs/store/files/9030839/example.zip)

output is:
<img width="897" alt="Screenshot 2022-07-01 at 19 03 14" src="https://user-images.githubusercontent.com/1037719/176947351-57ff18fa-13b0-451c-9b30-4ec970e949d7.png">

**Comment by anschm** [comment]
We have the same issue. Any progress on that? codeiuniquely provided a minimum reproducable example and a PR.

**Comment by arturovt** [comment]
It has been fixed, see the link PR.

**Comment by anschm** [comment]
Oh nice. It seems the PR is merged. So this can be closed and we can expect release 3.7.5 soon?

**Comment by fadingbeat** [comment]
I'm running on this issue when testing with Jest. I deleted node_modules and package-lock.json, and installed ngxs/store@3.7.4, doesn't fix it.

**Comment by arturovt** [comment]
It’s going to be released in 3.7.5.

**Comment by bendehghan** [comment]
When is 3.7.5 coming?
Thanks :)

**Comment by arturovt** [comment]
We're hoping to release it this week :)

**Comment by markwhitfeld** [comment]
Great news! [v3.7.5](https://github.com/ngxs/store/releases/tag/v3.7.5) has been released and it includes a fix for this issue.
We are closing this issue, but please re-open it if the issue is not resolved.
Please leave a comment in the [v3.7.5 release discussion](https://github.com/ngxs/store/discussions/1909) if you come across any regressions with respect to your issue.
