### ISSUE TITLE
Change detection stopped working in production

### ISSUE THREAD

**Issue by zygimantas** [ngxs/store#415]
### Versions
```
* ngxs: 3.1.1/3.1.2
* @angular/core: 6.0.3
```

### Repro steps

* In smart component, add ```@Select(ZooState.panda) public panda$!: Observable<Panda>;```
* In the same component, create subscription:
```this.panda$.subscribe(a => this.panda = a);```

### Observed behavior

When ```this.panda``` is changed, change detection does not happen in production environment and UI is not updated (*ngIf="panda").

### Desired behavior

Change detection should happen.

### Mention any other details that might be useful (optional)

It works as expected in 3.0.1 - all environments, 3.1.1/3.1.2 - development environment.
There is NO ChangeDetectionStrategy.OnPush set on component.

**Comment by ufoscout** [comment]
I have the same issue. The only workaround I found to make it work is to force angular to refresh manually calling ApplicationRef.tick(). For example:

```
@State<HomeStateModel>({
  name: 'home',
  defaults: new HomeStateModel(),
})
export class HomeState {

  constructor(private service: MyHttpService, private ref: ApplicationRef) {
  }

  @Action(events.CreateCluster)
  createCluster({ getState, setState }: StateContext<HomeStateModel>, { payload }: events.CreateCluster) {
    return this.service.doSomething(payload).pipe(
      tap(nodes => {
        const state = getState();
        setState({
          ...state,
          nodes: nodes
        });
        this.ref.tick(); // FORCE A REFRESH HERE
      }
      ),
      catchError(err => {
        this.ref.tick(); // FORCE A REFRESH HERE
        return of("error message")
      })
    )
  }
```

**Comment by amcdnl** [comment]
1) I don’t understand why you would make a subscribe like that vs just use a async pipe
2) this is introduced because of zone issue. We need to return select subscribe to the zone. I’ll make a patch shortly

**Comment by zygimantas** [comment]
1. Because ```this.panda``` is used in button click handling/hammerjs/ngOnChanges methods in component.

**Comment by amcdnl** [comment]
Gotcha, thanks for clarification.

**Comment by amcdnl** [comment]
should be fixed in 3.1.3

**Comment by ufoscout** [comment]
@amcdnl 
The error is still reproducible in 3.1.3.

This is the bad behavior that we have:
- step 1: trigger an action that changes the state
- step 2: expects the UI to display the updated data, but it does not happen
- step 3: if we click anywhere on the screen, then the UI is updated and the new data is visible

Everything works as expected with 3.0.1.

**Comment by amcdnl** [comment]
Can you make a SB issue?

**Comment by zygimantas** [comment]
Just letting you know that my issue was solved with 3.1.3. Thanks!

**Comment by ufoscout** [comment]
@amcdnl 
You can find a repro here:
https://github.com/ufoscout/WeWeb

Steps to reproduce:
- clone the repo
- enter the "frontend/Angular-Typescript/" folder (ignore all the rest)
- build it: `npm install`
- run it: `npm start`
- browse to localhost:4200
- In the navbar there is a language selector, change the language from "it" to "en"

Wrong behavior:
the UI still displays "Ciao Mondo" (Italian) instead of "Hello World" (English). If you click anywhere on the screen, then "Hello World" is displayed.

If you downgrade from
`"@ngxs/store": "^3.1.3"`
to 
`"@ngxs/store": "3.0.1"`
then the issue disappears and everything works as expected.

**Comment by amcdnl** [comment]
@ufoscout - is it still happening for you in 3.1.3?

**Comment by ufoscout** [comment]
@amcdnl 
yes, the bug is still present in 3.1.3. Please check my previous comment in which I provided a reproducer.
There is, however, a difference between the behavior of 3.1.2 and 3.1.3; in fact:
- with 3.1.2 the UI is never refreshed after a change in the state
- with 3.1.3 the UI is refreshed after a click on the screen (please note that the click is required only after the first state change, for subsequent changes the UI is refreshed as expected with no need to click).

**Comment by amcdnl** [comment]
@ufoscout - Check my updated answer.

**Comment by jhonland** [comment]
I have a similar problem in my own project, I tried to debug using the Actions handler from the Actions import form ngxs/store, I am subscribing in the component and using the pipe ofActionDispatched() in that subscribe I console.log the value, the first time that the component is instantiated the UI gets updated, but for some reason after a navigate to other route and then return to the initial route and try again, the same ofActionDispatched subscription function console.logs the value but the UI wont update unless I do as @ufoscout  says, to use tick() inside the subscription function.
Side note I am subscribed to ofActionSuccessful over the same action and after navigating to other route and returning to the initial one, it Updates the console.log value as expected and the UI gets updated also, with no use of Tick() method!!
I am using 3.1.3, have not tried downgrading.

**Comment by jhonland** [comment]
@amcdnl I just tested with version 3.0.1 and it worked out.

**Comment by juracy** [comment]
I think I have the same issue with mat-dialog (@angular/material): https://ngxs-mat-dialog-issue.stackblitz.io

And It worked perfectly with version 3.0.1

Using dispatch button, the dialog is showed, but the buttons cancel and ok, don't work correctly ...
The direct button shows same dialog without using @ngxs, and everything works...

**Comment by amcdnl** [comment]
@juracy - Your doing the same thing as him, you have code like:

```
  @Action(ConfirmAsk)
  ask(ctx: StateContext<ConfirmModelState>, action: ConfirmAsk) {
    this.uiAsk(action.message)
    ctx.setState({message: action.message})
  }

  uiAsk(message: string) {
    this.dialog.open(ConfirmDialogComponent, {
      width: '50%',
      data: { message: message },
    })
  }
```

That function should NOT live in your state. You should use the action stream to subscribe and react. This is actually a good thing this is happening to weed out these anti-patterns.

Unless someone says otherwise, I'm going to close this because it seems like its working for the appropriate cases now.

**Comment by juracy** [comment]
@amcdnl I also tried with action handlers and I haven't got success anyway...

I've just updated my example with handler, and the same problem remains...
https://ngxs-mat-dialog-issue.stackblitz.io

**Comment by juracy** [comment]
I could manage some workarounds:
- ApplicationRef.tick() in click handlers of buttons
- Call MatDialog.open in ngZone.run, in action handler or in state class, whatever.  I have peep in https://github.com/ngxs/store/blob/01c499f1e33a40ffebbf66ffbb46fcadb6b17d9b/packages/router-plugin/src/router.state.ts#L55

**Comment by juracy** [comment]
@jhonland like I said, my last example was updated in https://ngxs-mat-dialog-issue.stackblitz.io and I took off all side effects in the state class, even though, the problem remains ... I'm using o action stream now!

And in your example about router, nowadays it's working using ngZone.run like you can see in @ngxs/router-plugin: https://github.com/ngxs/store/blob/01c499f1e33a40ffebbf66ffbb46fcadb6b17d9b/packages/router-plugin/src/router.state.ts#L55

I don't believe that is the best approach anyway...

**Comment by amcdnl** [comment]
@juracy - I looked at your example and it seems to work to me? What am i missing?

Also, is this your real use case? It feels a bit odd to put a confirm state in a global state container like that.

**Comment by juracy** [comment]
@amcdnl sorry, steps:
1 - Click on dispatch button
2 - Click on Cancel action button in dialog

Expected behavior: log a message in console and **close dialog**

**Comment by ufoscout** [comment]
@amcdnl 
Moving the language selection from the state, as you suggested, solved that particular the issue; nevertheless, there are still use cases that work fine in 3.0.1 but not in 3.1.3. 
For example, I have a spinner image to be displayed while certain actions are running. in 3.0.1 this works as expected:
```typescript
  @Action(events.Login)
  login(ctx: StateContext<AuthStateModel>, {payload}: events.Login) {
    this.spinner.show();
    return this.loginService.login(payload).pipe(
      map(response => {
        this.spinner.hide();
        ctx.dispatch(new events.SetAuthData(response));
      }),
      catchError(err => {
        this.spinner.hide();
        return throwError(err);
      })
     );
  }
```

but in 3.1.3 the spinner is not shown. Moving the spinner from the state to somewhere else is not easy in this case. In fact, I cannot create a global interceptor since I need it only for some actions and create a special subscription to the Action Dispatched and Action Completed for each interested action seems really overcomplex for this simple task.
Is there any technical reason to not re-enable the same behavior of 3.0.1?

**Comment by juracy** [comment]
@ufoscout my two cents:
1 - Move the spinner interaction to a handler (action stream), that's the best practice
2 - Even though, run interaction with UI within ngZone (at least, it's my current workaround)

**Comment by amcdnl** [comment]
@ufoscout - The state is not supposed to interact w/ the UI. Hiding the spinner/etc is UI related and since we run state outside of zone it will not fire. Those should be action handlers or driven by state in the UI.

**Comment by markwhitfeld** [comment]
@amcdnl I can confirm that there is a bug if you use the action stream. 
It is because the action stream is not returning in the angular zone. I will submit a fix today.

@juracy See your sample with a temp workaround to get it working:
https://stackblitz.com/edit/ngxs-mat-dialog-issue-eo2aqj?file=src/app/confirm/confirm-handler.ts

Also, see a sample repro here of the issue and potential workarounds until it is fixed:
https://stackblitz.com/edit/ngxs-actionstream-bug-repro?file=app/app.component.ts

**Comment by juracy** [comment]
@markwhitfeld thanks! I had already been using ngZone! But I thought it's wrong or at least weird!

**Comment by markwhitfeld** [comment]
Confirmed fixed with latest dev package:
https://stackblitz.com/edit/ngxs-actionstream-bug-repro-fixed?file=app/app.component.ts

**Comment by jeffkenz89** [comment]
just want to let you know ngxs 3.14 still has this  like @juracy bug,after update to 3.14 NGXS/store@dev the bug is fix

**Comment by MurhafSousli** [comment]
@jeffkenz89 This is not a bug, when you want to update the UI from the state code use the following
```ts
this.ngZone.run(() => {

  this.dialog.open(ErrorDialogComponent, {
     width: '250px',
     data: payload.error.message,
     disableClose: true
  });

});
```
