### ISSUE TITLE
Store doesn't work in IE (3.4.3 only)

### ISSUE THREAD

**Issue by junimohano** [ngxs/store#923]
## I'm submitting a...

<pre><code>
[x] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Performance issue
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => https://github.com/ngxs/store/blob/master/CONTRIBUTING.md
[ ] Other... Please describe:
</code></pre>

## Current behavior
got errors in IE
```
action @@INIT @ 15:47:34.450
   TypeError: Object doesn't support property or method 'entries'
      {
         [functions]: ,
         __proto__: { },
         description: "Object doesn't support property or method 'entries'",
         message: "Object doesn't support property or method 'entries'",
         name: "TypeError",
         number: -2146827850,
         stack: "TypeError: Object doesn't support property or method 'entries'
   at NgxsLoggerPlugin.prototype._hasPayload (http://localhost:4200/vendor.js:151590:5)
   at NgxsLoggerPlugin.prototype.handle (http://localhost:4200/vendor.js:151503:5)
   at Anonymous function (http://localhost:4200/vendor.js:153835:1)
   at Anonymous function (http://localhost:4200/vendor.js:153844:9)
   at NgxsReduxDevtoolsPlugin.prototype.handle (http://localhost:4200/vendor.js:150173:9)
   at Anonymous function (http://localhost:4200/vendor.js:153835:1)
   at InternalDispatcher.prototype.dispatchSingle (http://localhost:4200/vendor.js:154028:5)
   at InternalDispatcher.prototype.dispatchByEvents (http://localhost:4200/vendor.js:154009:9)
   at Anonymous function (http://localhost:4200/vendor.js:153973:9)
   at ZoneDelegate.prototype.invoke (http://localhost:4200/polyfills.js:7909:13)",
         Symbol(INITIAL_VALUE)_h.v896nohb8f2: undefined,
         Symbol(rxSubscriber)_g.v896nohb8f2: undefined,
         Symbol(rxSubscriber)_i.v896nohb8f2: undefined
      }
```

## Expected behavior
should work in IE as well
3.4.1 works but 3.4.3

## Minimal reproduction of the problem with instructions
install 3.4.3 and go IE

## Environment

<pre><code>
Libs:
- @angular/core version: 7.2.0
- @ngxs/store version: 3.4.3

Browser:
- [ ] Chrome (desktop) version XX
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [x] IE version 11.379.17763.0
- [ ] Edge version XX
 
For Tooling issues:
- Node version: 10.15.1
- Platform:  windows 10

**Comment by arturovt** [comment]
@junimohano Maybe I'm missing something, but `Object.entries` is not supported in the IE and you need a polyfill.

**Comment by junimohano** [comment]
@arturovt 

I don't care IE doesn't support Object.entries or not,

The problem is that it broke IE when I upgrade to 3.4.3 as 3.4.1 works fine which means regression is failed.

Patch version became break changes now.

**Comment by arturovt** [comment]
@junimohano 
Don't be rude please, we just discuss.

**Comment by junimohano** [comment]
@arturovt I didn't say strongly maybe my text looks too straight to you?

sorry if you feel like that :)

**Comment by arturovt** [comment]
@junimohano 
Could you try the latest published `@dev` version? The latest is `3.4.3-dev.master-0f1e084`

**Comment by arturovt** [comment]
@junimohano ping

**Comment by junimohano** [comment]
I tested it and that error goes away (that error was caused by @ngxs/logger-plugin) - thanks !

but seems different issue came out. 
there is now infinite page loop in only IE (only happens when I upgrade @ngxs/router-plugin to either 3.4.3 or 3.4.3-dev.master-0f1e084).
3.4.1 of @ngxs/router-plugin is okay.
Is there some break changes? 
I am using angular-oauth2-oidc extra library which uses redirect url from Identity provider after login.

**Comment by arturovt** [comment]
@junimohano 
What kind of infinite loop?

**Comment by arturovt** [comment]
@junimohano 
Can we close this as it's connected to the `@ngxs/logger-plugin`?

**Comment by junimohano** [comment]
@arturovt hard to explain about infinite loop as I have no idea why.

yes as long as this ticket is connected to @ngxs/logger-plugin, you can close it.

**Comment by mackelito** [comment]
Sorry for posting on a old ticket.. but should this not be fixed?
Or at the very least documented?

**Comment by markwhitfeld** [comment]
The original issue was fixed (see pr 931).
The infinite loop needed a repro and a separate issue logged.

**Comment by mackelito** [comment]
Ok.. but this plugin still doesn't work in IE11 due to using 'entries' :)

**Comment by arturovt** [comment]
@mackelito 

What version of `@ngxs/logger-plugin` are you using? Because there is no `entries` :)

**Comment by mackelito** [comment]
"@ngxs/logger-plugin": "^3.3.4",

**Comment by splincode** [comment]
@mackelito it's reproduce?

**Comment by mackelito** [comment]
Just tried it.. same issue 
<img width="1089" alt="Screenshot 2019-05-20 at 16 16 05" src="https://user-images.githubusercontent.com/598463/58028238-9921b500-7b1a-11e9-8b19-a74f6fb81454.png">

**Comment by splincode** [comment]
@mackelito show me your version in logger-plugin in

/node_modules/@ngxs/logger-plugin/package.json

**Comment by arturovt** [comment]
Agreed with @splincode 

We don't have `Object.entries` in any part of the code :smile:

**Comment by mackelito** [comment]
```
{
  "$schema": "../../node_modules/ng-packagr/package.schema.json",
  "name": "@ngxs/logger-plugin",
  "description": "logger plugin for @ngxs/store",
  "version": "3.4.3",
  "sideEffects": true,
  "peerDependencies": {
    "@ngxs/store": "^3.4.3 || ^3.4.3-dev",
    "@angular/core": ">=5.0.0 <8.0.0",
    "rxjs": ">=6.0.0 || ^5.6.0-forward-compat.4"
  },
  "main": "bundles/ngxs-logger-plugin.umd.js",
  "module": "fesm5/ngxs-logger-plugin.js",
  "es2015": "fesm2015/ngxs-logger-plugin.js",
  "esm5": "esm5/ngxs-logger-plugin.js",
  "esm2015": "esm2015/ngxs-logger-plugin.js",
  "fesm5": "fesm5/ngxs-logger-plugin.js",
  "fesm2015": "fesm2015/ngxs-logger-plugin.js",
  "typings": "ngxs-logger-plugin.d.ts",
  "metadata": "ngxs-logger-plugin.metadata.json",
  "dependencies": {
    "tslib": "^1.9.0"
  },
  "repository": {
    "type": "git",
    "url": "git+https://github.com/ngxs/store.git"
  },
  "keywords": [
    "ngxs",
    "redux",
    "state",
    "rxjs",
    "angular",
    "ngx",
    "angular2",
    "cqrs",
    "store",
    "state-management",
    "event-stream"
  ],
  "author": "Austin McDaniel",
  "contributors": [
    {
      "name": "Danny Blue"
    },
    {
      "name": "Leon Radley"
    },
    {
      "name": "Mark Whitfeld"
    },
    {
      "name": "Maxim Ivanov"
    }
  ],
  "license": "MIT",
  "bugs": {
    "url": "https://github.com/ngxs/store/issues"
  },
  "homepage": "https://github.com/ngxs/store#readme"
}

**Comment by splincode** [comment]
![image](https://user-images.githubusercontent.com/12021443/58030772-ce80cf80-7b27-11e9-9b22-42935b681c1e.png)

this does not work in the latest version, it is available only in 3.4@dev

**Comment by splincode** [comment]
Released in 3.5.0
